site_name: Audio AI Explainer
theme:
  name: material
  # (optional but helpful during setup)
  features:
    - navigation.instant: false   # prevents partial reload issues with third-party scripts

extra_css:
  - https://pyscript.net/releases/2025.7.3/core.css

extra_javascript:
  - path: https://pyscript.net/releases/2025.7.3/core.js
    type: module

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - About: index.md
  - What is audio?: what-is-audio.md
  - Digital audio representations: how-is-audio-represented-digitally.md
  - How older ML models work: how-older-audio-models-work.md
  - Speech, language, and semantics: speech-language-and-semantics.md
  - Audio in LLMs: audio-in-llms.md
  - Legal and regulatory issues: audio-ai-legal-and-regulatory-issues.md
  - Major open research questions: major-open-questions-for-audio-ai.md
  - About: about.md