site_name: Audio AI Explainer
theme:
  name: material

extra_css:
  - https://pyscript.net/releases/2025.7.3/core.css

extra_javascript:
  - path: https://pyscript.net/releases/2025.7.3/core.js
    type: module
