site_name: Audio AI Explainer
theme:
  name: material
  # (optional but helpful during setup)
  features:
    - navigation.instant: false   # prevents partial reload issues with third-party scripts

extra_css:
  - https://pyscript.net/releases/2025.7.3/core.css

extra_javascript:
  - path: https://pyscript.net/releases/2025.7.3/core.js
    type: module

nav:
  - Home: index.md
  - What is audio?: what-is-audio.md
  - How is audio represented digitally?: how-is-audio-represented-digitally.md
  - How Older Audio Models Work: how-older-audio-models-work.md